### PR TITLE
Broker configs: Display a tooltip about the source of the property #2679

### PR DESCRIPTION
**Pull request by David-DB88**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Broker configs: Display a tooltip about the source of the property 

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by workshur — CHANGES_REQUESTED** [review]
1. let's call it Tooltip instead of TooltipComponent
2. This component should live in components/common folder

**Review by workshur — APPROVED** [review]

**Comment by workshur** [comment]
@hHaarolean, this one is ready for QA

**Review by workshur — APPROVED** [review]

**Comment by Mgrdich** [comment]
Here the tool-tip library should change cause in their github page documentation they recommend using another library since this library is just a wrapper around vanilla js Lib , and it will not be efficient using it.

@Haarolean  i can replace this library.

**Review by Mgrdich — APPROVED** [review]

**Comment by Mgrdich** [comment]
@Haarolean the library is replaced , this one is ready for QA

**Review by Haarolean — APPROVED** [review]

**Pull request merged**
