### PR TITLE
Fixed ingress template for k8s version older than 1.19

### PR DESCRIPTION
**Pull request by joseacl**
**What changes did you make?** 
The changes in this PR aims to fix this issue https://github.com/provectus/kafka-ui/issues/2317

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [x] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

### CODE REVIEW

**Comment by Haarolean** [comment]
@azatsafin PTAL

**Comment by joseacl** [comment]
I've just realized that it exists a test for Kubernetes manifests in the workflow folder. So I thought that could be helpful to have this change covered by the integration test.

**Review by RustamGimadiev — APPROVED** [review]

**Review by azatsafin — APPROVED** [review]
Checked manually, looks good for me

**Comment by Haarolean** [comment]
@joseacl thanks for the contribution!

**Comment by sgolod** [comment]
This changes breaks compatibility with GKE clusters versions (GKE use -gke.XXXX as suffix for version).
It can be solved when use semver comparision to full version ("1.19" -> "1.19.0-0")
```
(trimPrefix "v" .Capabilities.KubeVersion.Version | semverCompare ">= 1.19" ) =>
(trimPrefix "v" .Capabilities.KubeVersion.Version | semverCompare ">= 1.19.0-0" )
```

**Comment by joseacl** [comment]
More likely I'm missing something, but I don't see why this change **breaks compatibility** with GKE. 
The change you suggested will improve the fix, but currently what can happend is the same as before, and it's that the ingress template will be render using `apiVersion: networking.k8s.io/v1` (which is incompatible with k8s version lower than 1.19)

I've tested it using this command:

```
helm template --kube-version 1.19.0-0 --set ingress.enabled=true -f values.yaml  .
```

**Pull request merged**
