### PR TITLE
FE: Fix active controller badge on invalid node

### LINKED ISSUE #3614: Active controller badge on invalid node
In `/api/clusters/local/stats` endpoint `activeControllers` **is an id of a node** that is _Active controller_ node. Now green badge is rendered on another node or not even shown sometimes.

Version: master commit [de21721](https://github.com/provectus/kafka-ui/commit/de21721)

Screenshot 2023-04-03 at 12 24 34

### PR DESCRIPTION
**Pull request by moremagic**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Fixes #3614

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [x] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Haarolean** [comment]
@moremagic hey, can we add a test for this?

**Comment by moremagic** [comment]
@Haarolean I'll try for create test code.

**Comment by moremagic** [comment]
Changed BrokerID in test data to avoid confusion with test case row index.
Changed relevant test cases.

**Comment by moremagic** [comment]
@Haarolean 

Added test. please check

**Comment by Haarolean** [comment]
@moremagic thank you very much!

**Pull request merged**
