### PR TITLE
Update contributing guidelines

### PR DESCRIPTION
**Pull request by Haarolean**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing applications:)

**What changes did you make?** (Give an overview)
Updated contributing guidelines

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "X" next to an item)

- [x] No need to
- [ ] Manually(please, describe, when necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "X" next to an item, otherwise PR will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings(e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

### CODE REVIEW

**Comment by Haarolean** [comment]
Let me know if there's anything to add. Or feel free to commit.

**Review by IldarAlmakaev — APPROVED** [review]

**Comment by germanosin** [comment]
Great! Let's also add PR naming convention.

**Review by workshur — APPROVED** [review]

**Comment by germanosin** [comment]
And looks like we need convention for rest paths, query var names, Model names in the contract

**Review by iliax — APPROVED** [review]

**Comment by Haarolean** [comment]
> And looks like we need convention for rest paths, query var names, Model names in the contract

@germanosin any specific suggestions for that? I have no idea what to write :)

**Comment by germanosin** [comment]
> > And looks like we need convention for rest paths, query var names, Model names in the contract
> 
> @germanosin any specific suggestions for that? I have no idea what to write :)

rest paths: lowercase, should include only plural nouns, multiple words in one path segment should be divided by dash
query var names: lowercase, camelCase
Model names: camelCase, plural nouns,

**Comment by Haarolean** [comment]
@germanosin done, please take a look.

**Comment by germanosin** [comment]
Great work!

**Pull request merged**
