### PR TITLE
Kafka Connect: Implement basic auth

### PR DESCRIPTION
**Pull request by gaddam1987**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)
There wont be any breaking changes

**What changes did you make?** (Give an overview)
Enable to connect to Kafka-connect-cluster which has basic auth enabled

**Is there anything you'd like reviewers to focus on?**
I have updated the swagger doc for connect, it will be nice if someone can have a look at it

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary) 
We are using kafka-ui in our local environment where we connect to kafka-connect-cluster which has basic auth enabled
- [x] Unit checks
- [x] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works (I couldn't add new tests because the way the abstract test class is used)
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Haarolean** [comment]
@gaddam1987 you've probably not pushed at all considering the history :) feel free to ask any questions regarding that

**Comment by gaddam1987** [comment]
@Haarolean 
I tried to update but for some reason i don't know it didn't reflect, you can see the change in commit hash from previous pull request.
New commit hash: 4705bfacbb96f5a82692c495c2e869e61a07e1b1
Old commit hash: 72b36c89789347f84b6818ef85f7e8f92a0b3b9b

Steps i followed:
I need to remove 2 files from the commit 72b36c89789347f84b6818ef85f7e8f92a0b3b9b as i have accidentally added some new lines. 
kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java
kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/SchemaRegistryAwareRecordSerDe.java

And pushed that changes with force push: git add . && git commit --amend --no-edit && git push -f  (This change didnt reflect in the pull request)

Then i did a rebase to remove the conflict: git rebase origin/master and pushed using git push -f which didn't reflect any changes in the pull request too.

I could be missing something :)

**Comment by Haarolean** [comment]
@gaddam1987 dunno what you've done actually, any forced push is clearly visible in PR history anyway, but there were none.

**Review by Haarolean — APPROVED** [review]

**Comment by Haarolean** [comment]
@gaddam1987 please document new env variables somewhere (env params list at the end of README, corresponding docker-compose examples)

**Comment by gaddam1987** [comment]
@Haarolean Hi, i have updated the doc can you please check it once

**Review by Haarolean — APPROVED** [review]
@gaddam1987 thanks! But please don't squash commits in the future if that's not necessary, otherwise we have to review all the files over and over again (they're not marked as viewed)

**Comment by gaddam1987** [comment]
> @gaddam1987 thanks! But please don't squash commits in the future if that's not necessary, otherwise we have to review all the files over and over again (they're not marked as viewed)

Sorry for that, i am used to this flow in my org but will remember next time not to squash commits. Thanks for merging the change :)

**Pull request merged**
