### PR TITLE
Unify tabs placement

### LINKED ISSUE #2332: Unify tabs placement
e.g. connector overview page:
image
tabs are placed above the panes and the page looks empty and weird. Let's unify **all the views** with this approach:
image
broker overview page panes are located below the tabs therefore "overview" tab is no longer required

### PR DESCRIPTION
**Pull request by habrahamyanpro**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

- fixes #2332

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by workshur — APPROVED** [review]

**Comment by workshur** [comment]
@habrahamyanpro pls revert changes for topics section.

**Review by workshur — CHANGES_REQUESTED** [review]
We need to revert layout change for topic section. For messages page it is super important to have slim header

**Review by workshur — APPROVED** [review]

**Comment by workshur** [comment]
🚢 it!

**Comment by Haarolean** [comment]
@VladSenyuta @provectus/kafka-qa seems like we broke something here :)

**Comment by VladSenyuta** [comment]
> @VladSenyuta @provectus/kafka-qa seems like we broke something here :)

fixed

**Review by VladSenyuta — APPROVED** [review]

**Pull request merged**
