### PR TITLE
KYCX-2330: rename Schema name to subject

### PR DESCRIPTION
**Pull request by vitalymatyushik**
- [x] **Breaking change?** No

**What changes did you make?** (Give an overview)
Schema name was renamed to Subject

**Is there anything you'd like reviewers to focus on?**
The only change was on Schema Registry creation view

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [x] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Haarolean** [comment]
There are a lot of other places:

schema name -> subject
image
image

**Comment by vitalymatyushik** [comment]
@Haarolean thank you for pointing out! I've found these 2 pages, not sure where are the others

**Comment by vitalymatyushik** [comment]
@Haarolean could you please suggest next steps?

**Comment by Haarolean** [comment]
@vitalymatyushik this might be enough :))

@armenuikafka wanna take a look before we merge?

**Comment by armenuikafka** [comment]
PR was closed accidentally, testing in progress

**Review by workshur — APPROVED** [review]

**Review by armenuikafka — CHANGES_REQUESTED** [review]
please, rename schema to subject for empty case too.

Untitled 2

**Review by Mgrdich — APPROVED** [review]

**Pull request closed without merging**
