### PR TITLE
#168 Resolve thread leak when creating Kafka admin client

### PR DESCRIPTION
**Pull request by RamazanYapparov**
Before the fix in 5 minutes after launch:
изображение

After fix in 6 minutes after launch:
изображение

### CODE REVIEW

**Review by IldarAlmakaev — COMMENTED** [review]
Does it resolve a thread leak?

**Comment by RamazanYapparov** [comment]
@IldarAlmakaev yes it does
updated the description

**Review by IldarAlmakaev — APPROVED** [review]
Good job!

**Review by germanosin — APPROVED** [review]
Nice catch

**Pull request merged**
