### PR TITLE
Fix smart filters multiple conditions

### PR DESCRIPTION
**Pull request by KriKiparoidze**
- [x] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

Fix smart filter with multiple conditions #2375

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

Screenshot 2022-08-04 at 22 45 08

Screenshot 2022-08-04 at 22 44 46

### CODE REVIEW

**Comment by workshur** [comment]
@armenuikafka @Haarolean pls review it works as expected

**Review by workshur — APPROVED** [review]

**Comment by mk-khan** [comment]
@anezboretskiy  @Haarolean  thanks for pushing this to master, I have downloaded the new docker image from kafka-ui:master, however, when i have the filter set to "value.Id == "SiR_SG00079XX1.G1" && value.Idx == 1003" then i am still seeing values for value.Idx 1003 and 1006. Is there something I am missing while using the filter ?

**Comment by Haarolean** [comment]
@mk-khan nothing has been pushed so far

**Comment by mk-khan** [comment]
@Haarolean ok, looking forward this to be merged to master at least. Thanks again

**Comment by mk-khan** [comment]
@Haarolean any chance this PR can be merged to master? I needed this filter capability to test some data issues we are having.. appreciate if someone can merge it..

**Comment by Haarolean** [comment]
@mk-khan It will get merged the moment review is done

**Comment by armenuikafka** [comment]
Filter works correctly with 2 conditions in http://pr2400.internal.kafka-ui.provectus.io/

**Comment by mk-khan** [comment]
@armenuikafka, I tried to build from the master and still having the same issue. out of two filters only one get applied and the other does not. Could you please let me know if there is other docker image that i can try to make this work on our end.

**Comment by armenuikafka** [comment]
@mk-khan hey! let's try to check once it will be merged to master. If the issue will be actual after merge, let us know.

**Comment by Haarolean** [comment]
@KriKiparoidze let's resolve the conflicts and merge

**Comment by Haarolean** [comment]
@mk-khan available as `master`-labeled docker image

**Comment by mk-khan** [comment]
Thank you so much, I will update my build and let you know if any issues.

**Pull request merged**
