### PR TITLE
FE: fix dropdown on topics (issue#3896)

### PR DESCRIPTION
**Pull request by Ppojin**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [x] No need to
- [x] Manually (please, describe, if necessary)
  - follow with [kafka-ui-react-app getting-started](https://github.com/provectus/kafka-ui/tree/master/kafka-ui-react-app#getting-started)
  - click "Dropdown Toggle" button
- [x] Unit checks
- [x] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**
IMG_0369

### CODE REVIEW

**Comment by Ppojin** [comment]
fixed on react-menu@3.3.0[src/__tests__/SSR.test.js](https://github.com/szhsin/react-menu/pull/553/files#diff-dbe48b7e1336f7b36a23522b891ca77fc0670da38b1f6410e3b7e64c00fc127d)

**Comment by Haarolean** [comment]
Hi @Ppojin, could you elaborate, on what has been fixed exactly? What's the issue? I see  no linked issues and the problem is not obvious.

**Review by workshur — APPROVED** [review]

**Comment by Ppojin** [comment]
Hello @Haarolean, linked issue is [issiue#3896](https://github.com/provectus/kafka-ui/issues/3896).
I don't know how to link issue on Github. Sorry for making you find.

**Review by Haarolean — APPROVED** [review]

**Comment by Haarolean** [comment]
@Ppojin thank you for the contribution!

You can link issues via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Please edit the PR so the build passes and we can merge :)

image

**Pull request merged**
