### PR TITLE
feat(kafka-connect): Implement kafka-connect mTLS configuration

### LINKED ISSUE #2616: Support passing properties to Kafka Connect client
### Which version of the app are you running?
Tag: `v0.4.0` and `master@d9e74deb287e7b81172c6988dd0f99b1a97d9036`

### Is your proposal related to a problem?
Currently it's not possible to configure a Kafka Connect component that has TLS Client Auth required but there could be also other settings that need to be passed to the Kafka Connect Client.

### Describe the solution you'd like
I would like to propose adding a `Properties` field to the `model.KafkaConnectCluster` class like the `model.KafkaCluster` and use the properties in the client instantiation.

Therefore the Kafka Connect component could be configured in the following way to allow TLS Client Auth:
```plaintext
KAFKA_CLUSTERS_0_KAFKACONNECT_0_PROPERTIES_SECURITY_PROTOCOL=SSL
KAFKA_CLUSTERS_0_KAFKACONNECT_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION=ca.jks
KAFKA_CLUSTERS_0_KAFKACONNECT_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD=xxxx
KAFKA_CLUSTERS_0_KAFKACONNECT_0_PROPERTIES_SSL_KEYSTORE_LOCATION=foobar.jks
KAFKA_CLUSTERS_0_KAFKACONNECT_0_PROPERTIES_SSL_KEYSTORE_PASSWORD=xxxx
```

### Describe alternatives you've considered
N/A

### Additional context
This issue is propably related to #930.

If I get some spare time, I will have a look by myself at it and create a PR.

### PR DESCRIPTION
**Pull request by djboris9**
**What changes did you make?** (Give an overview)
I extended the kafka-connect configuration with keystore and truststore locations and passwords. These properties are passed to the webclient. It enables the user to connect Kafka-UI to a kafka-connect instance that uses a special CA (using truststore) or via mTLS (using truststore and keystore).

It fixes #2616 

**Is there anything you'd like reviewers to focus on?**
My Java is a bit rusty. Therefore I'm happy for a comment if you find better ways to implement this.

It is similar to #2832 

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

Manual test against a local kafka-connect with mTLS.

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

I didn't create a test for it as requested by I have added tests that prove my fix is effective or that my feature works because I don't have a plan where/how to start with it.

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by djboris9** [comment]
The documentation check is failing but it looks like a temporary network issue. Sadly I cannot run a retest.

**Comment by iliax** [comment]
@djboris9 can you pls also add docker compose sample where SR and Connected TLS is enabled ?

**Comment by djboris9** [comment]
Hi @iliax 
I refactored this PR to use the new `SecuredWebClient` and added a docker compose sample with TLS in between Kafka, Kafka-UI, Schema Registry and Kafka Connect. This also required new key material with added SANs for convenience.

**Comment by allanpaiste** [comment]
@djboris9 was expecting this very feature to be part of the default feature-set and was pleasantly surprised to find this PR. Kudos!

**Review by Haarolean — APPROVED** [review]

**Comment by Haarolean** [comment]
@djboris9 thank you!

**Pull request merged**
