### PR TITLE
Deploy OpenShift route for external communications using the Helm Chart

### PR DESCRIPTION
**Pull request by rmarting**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

This PR is created to support the enhacement identified in the provectus/kafka-ui-charts#4. It is an initial approach to cover that feature for OpenShift environments.

**Is there anything you'd like reviewers to focus on?**

Code format for the new Route template (I compared with the Ingress one, but just to double check that is aligned with the code formats)

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [X] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [X] Covered by existing automation

It was tested locally using a local OpenShift cluster (using [OpenShift Local](https://developers.redhat.com/products/openshift-local/overview)), and another remote cluster.

The `value.yaml` file used for my local tests was similar to:

```yaml
yamlApplicationConfig:
  kafka:
    clusters:
      - name: my-cluster
        bootstrapServers: my-kafka-kafka-bootstrap.amq-streams-demo.svc:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false

ingress:
  enabled: false
  host: kafka-ui-amq-streams-demo.apps-crc.testing

route:
  enabled: true
```

This is the command used to execute the Helm Chart:

```shell
helm upgrade --install kafka-ui charts/kafka-ui/ -f values.yaml --history-max 2
```

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [ ] My changes generate no new warnings (e.g. Sonar is happy)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Haarolean** [comment]
@Narekmat @provectus/kafka-devops PTAL :)

**Review by Narekmat — CHANGES_REQUESTED** [review]
@rmarting thank you for your changes.
Please increment version in Chart.yaml file to 0.6.4

**Comment by rmarting** [comment]
@Narekmat Done!!! Ready for your review! Thanks

**Comment by cadnce** [comment]
Are you aware that you can use ingress annotations to achieve the same effect? :)
I.e. `route.openshift.io/termination: reencrypt`

In my experience it is rare to include openshift specific features such as routes in generic helm charts.

**Comment by rmarting** [comment]
@cadnce you are right, however OpenShift routes is another way to expose externally services outside from the platform. I found many users using OpenShift routes to expose their services instead of the ingress objects, as from a platform point of view, it is very easy and you don't need to deal with the host entries. 

This PR is just to improve the helm chart to use this kind of object (optionally) for this kind of platform. I found other Helm Charts in the community including too.

**Comment by rmarting** [comment]
> @Narekmat Done!!! Ready for your review! Thanks
> 
> However, it seems that there is a conflict with the latest version in the `master` branch where the version defined is the `0.7.0` ... so should I upgrade the `Chart.yaml` file to `0.7.x`?

Any comment? Thanks!

**Review by Narekmat — CHANGES_REQUESTED** [review]
Please replace appVersion: to v0.7.0 and version 0.7.1

**Comment by rmarting** [comment]
> Please replace appVersion: to v0.7.0 and version 0.7.2

@Narekmat Done!

**Comment by rmarting** [comment]
@Narekmat This PR is ready for your review. Thanks!

**Comment by Haarolean** [comment]
We'll take a look why helm linter is failing.

**Comment by Haarolean** [comment]
@rmarting it seems that this logic is indeed very dependent on openshift, as our linter cannot validate the changes.
I suggest closing this PR unless you know a way to satisfy our linter :)

**Comment by rmarting** [comment]
@Haarolean please, dont close for now this PR. I have an idea about how to validate the route object, but I need some time to implement it. How long can be opened the PR before an automatic close? Thanks

**Comment by Haarolean** [comment]
@rmarting we'd need to reopen it in the [charts repo](https://github.com/provectus/kafka-ui-charts) anyway :)

**Comment by Haarolean** [comment]
https://github.com/provectus/kafka-ui-charts

**Comment by rmarting** [comment]
Ok! @Haarolean I will try to resolve it there with a new PR. Thanks for the heads up!

**Pull request closed without merging**
