### PR TITLE
Fix URL encoding while getting schemas 

### LINKED ISSUE #1995: No URL encoding while getting schemas
**Describe the bug**
We have subject with '/' sign in it, what causes exception after choosing 'Schema Registry' option. I can see that app requests for:
`GET https://schema-registry.nonprod.ipfdigital.io/subjects/apollo/commons/Header.proto/versions/latest`
so without proper URL encoding, and should be:
`https://schema-registry.nonprod.ipfdigital.io/subjects/apollo%2fcommons%2fHeader.proto/versions/latest`

In version 0.3.x everything works fine, something broke in 0.4.

**Screenshots**

image

**Exception**
`{"code":4009,"message":"No such schema apollo/commons/Header.proto with version latest","timestamp":1652860516935,"requestId":"5d9f795f-81176","fieldsErrors":null,"stackTrace":"com.provectus.kafka.ui.exception.SchemaNotFoundException: No such schema apollo/commons/Header.proto with version latest\n\tat com.provectus.kafka.ui.service.SchemaRegistryService.lambda$throwIfNotFoundStatus$20(SchemaRegistryService.java:238)\n\tSuppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: \nError has been observed at the following site(s):\n\t*__checkpoint ⇢ 404 from GET http://schema-registry-service:8081/subjects/apollo/commons/Header.proto/versions/latest [DefaultWebClient]\n\t*__checkpoint ⇢ Handler com.provectus.kafka.ui.controller.SchemasController#getSchemas(String, Integer, Integer, String, ServerWebExchange) [DispatcherHandler]\n\t*__checkpoint ⇢ com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]\n\t*__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ HTTP GET \"/api/clusters/nonprod-msk-cluster/schemas\" [ExceptionHandlingWebHandler]\nOriginal Stack Trace:\n\t\tat com.provectus.kafka.ui.service.SchemaRegistryService.lambda$throwIfNotFoundStatus$20(SchemaRegistryService.java:238)\n\t\tat org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec$StatusHandler.apply(DefaultWebClient.java:695)\n\t\tat org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec.applyStatusHandlers(DefaultWebClient.java:654)\n\t\tat org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec.handleBodyMono(DefaultWebClient.java:623)\n\t\tat org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec.lambda$bodyToMono$2(DefaultWebClient.java:541)\n\t\tat reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)\n\t\tat reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)\n\t\tat reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)\n\t\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)\n\t\tat reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)\n\t\tat reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)\n\t\tat reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)\n\t\tat reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)\n\t\tat reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)\n\t\tat reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:150)\n\t\tat reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:189)\n\t\tat reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)\n\t\tat reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)\n\t\tat reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:165)\n\t\tat reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:414)\n\t\tat reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:671)\n\t\tat reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onStateChange(DefaultPooledConnectionProvider.java:183)\n\t\tat reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onStateChange(DefaultPooledConnectionProvider.java:439)\n\t\tat reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:637)\n\t\tat reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\t\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\t\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)\n\t\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)\n\t\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)\n\t\tat io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)\n\t\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)\n\t\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\t\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\t\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\t\tat io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)\n\t\tat io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)\n\t\tat io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)\n\t\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)\n\t\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\t\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t\tat java.base/java.lang.Thread.run(Thread.java:830)\n"}`

### PR DESCRIPTION
**Pull request by shubhwip**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Use build instead of buildAndExpand to fix paths
Add Test for subject name with non ascii chars
Closes #1995

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [x] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by shubhwip** [comment]
Verified using below curl request.

**Request**
```curl 'http://localhost:8080/api/clusters/local/schemas' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: hubspotutk=055aa5178eca47cdc15c6b99ce18266b; _csrf=-SaG0njGKpRxTXLSOz4_DR95; x-csrf-token=ouPiKUdi-oGi7P6p7rDmd-c8AasZp4Me0ZWk; __hssrc=1; __hstc=181257784.055aa5178eca47cdc15c6b99ce18266b.1659782745939.1660737481596.1660746669953.4' \
  -H 'Origin: http://localhost:8080' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"subject":"test/test","schema":"\"schema\" : {\n\"name\" : \"shubham\"\n}","schemaType":"JSON"}' \
  --compressed
{"subject":"test/test","version":"1","id":1,"schema":"\"schema\"","compatibilityLevel":"BACKWARD","schemaType":"JSON"}%```


**Schema Registry Logs**
```
[2022-08-19 11:41:11,634] INFO Registering new schema: subject test/test, version null, id null, type JSON, schema size 33 (io.confluent.kafka.schemaregistry.rest.resources.SubjectVersionsResource)
[2022-08-19 11:41:11,864] INFO Wait to catch up until the offset at 2 (io.confluent.kafka.schemaregistry.storage.KafkaStore)
[2022-08-19 11:41:11,873] INFO Reached offset at 2 (io.confluent.kafka.schemaregistry.storage.KafkaStore)
[2022-08-19 11:41:12,199] INFO Wait to catch up until the offset at 3 (io.confluent.kafka.schemaregistry.storage.KafkaStore)
[2022-08-19 11:41:12,283] INFO Reached offset at 3 (io.confluent.kafka.schemaregistry.storage.KafkaStore)
[2022-08-19 11:41:12,821] INFO 172.29.0.7 - - [19/Aug/2022:11:41:11 +0000] "POST /subjects/test%2Ftest/versions HTTP/1.1" 200 8 "-" "ReactorNetty/1.0.19" POSTsT (io.confluent.rest-utils.requests)
[2022-08-19 11:41:13,643] INFO 172.29.0.7 - - [19/Aug/2022:11:41:13 +0000] "GET /config/test%2Ftest?defaultToGlobal=true HTTP/1.1" 200 53 "-" "ReactorNetty/1.0.19" GETsT (io.confluent.rest-utils.requests)
[2022-08-19 11:41:13,659] INFO 172.29.0.7 - - [19/Aug/2022:11:41:13 +0000] "GET /subjects/test%2Ftest/versions/latest HTTP/1.1" 200 84 "-" "ReactorNetty/1.0.19" GETsT (io.confluent.rest-utils.requests)```

**Comment by Haarolean** [comment]
@shubhwip hey, nice catch! Thanks for the contribution :)

**Comment by shubhwip** [comment]
@Haarolean Just curious why `backend / build-and-test (pull_request_target)` was failing with `KafkaConsumerGroupTests` ?

**Comment by Haarolean** [comment]
> @Haarolean Just curious why `backend / build-and-test (pull_request_target)` was failing with `KafkaConsumerGroupTests` ?

because it's a flaky test as it seems :))

**Comment by Haarolean** [comment]
> @Haarolean Just curious why `backend / build-and-test (pull_request_target)` was failing with `KafkaConsumerGroupTests` ?
> 
> Also since we don't allow `subject` with names with non ascii character from `kafka-ui` application but then why do we want to allow them via `service endpoints` ?

regarding the naming, I suppose we should allow it everywhere if that's a thing (as it seems).

**Comment by shubhwip** [comment]
> > @Haarolean Just curious why `backend / build-and-test (pull_request_target)` was failing with `KafkaConsumerGroupTests` ?
> > Also since we don't allow `subject` with names with non ascii character from `kafka-ui` application but then why do we want to allow them via `service endpoints` ?
> 
> regarding the naming, I suppose we should allow it everywhere if that's a thing (as it seems).

Awesome Can i create issue for that and submit PR for same ?

**Comment by Haarolean** [comment]
> > > @Haarolean Just curious why `backend / build-and-test (pull_request_target)` was failing with `KafkaConsumerGroupTests` ?
> > > Also since we don't allow `subject` with names with non ascii character from `kafka-ui` application but then why do we want to allow them via `service endpoints` ?
> > 
> > 
> > regarding the naming, I suppose we should allow it everywhere if that's a thing (as it seems).
> 
> Awesome can i create issue for that and submit PR for same ?

Yes, sure, please do :)

**Comment by shubhwip** [comment]
@Haarolean We would need one more fix here as while fetching the subject the URL is not encoded from client side and it is going like this `http://localhost:8080/ui/clusters/local/schemas/test/test` and it should go like this `http://localhost:8080/ui/clusters/local/schemas/test%2Ftest` to work properly.

**Comment by Haarolean** [comment]
> @Haarolean We would need one more fix here as while fetching the subject the URL is not encoded from client side and it is going like this `http://localhost:8080/ui/clusters/local/schemas/test/test` and it should go like this `http://localhost:8080/ui/clusters/local/schemas/test%2Ftest` to work properly.

okay, sounds about right. Feel free to push :)

**Comment by Haarolean** [comment]
> @Haarolean We would need one more fix here as while fetching the subject the URL params is not encoded from client side and it is going like this as shown in browser `http://localhost:8080/ui/clusters/local/schemas/test/test` and it should go like this `http://localhost:8080/ui/clusters/local/schemas/test%2Ftest` to work properly.

okay, we'll do this in a separate frontend PR I guess. If you're familiar with react/ts, you can do that as well :)

**Comment by shubhwip** [comment]
> while fetching the subject the URL params is not encoded from client side and it is going like this as shown in browser `http://localhost:8080/ui/clusters/local/schemas/test/test` and it should go like this `http://localhost:8080/ui/clusters/local/schemas/test%2Ftest` to work properly.

Ok will create issue and submit PR.

**Comment by Haarolean** [comment]
Let's wait for the frontend

**Review by Haarolean — APPROVED** [review]

**Review by Haarolean — APPROVED** [review]

**Pull request merged**
