### PR TITLE
Fix validation message for Topic name field

### LINKED ISSUE #2203: In case of using "," symbol system doesn't give the validation message for Topic name field
**Describe the bug**
In case of using "," symbol system doesn't give the validation message for Topic name field

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topics
2. Add a Topic
3. Input the ";" symbol into Topic name field
4. Make sure validation message appears "Only alphanumeric, _, -, and . allowed"
5. Input the "," symbol into Topic name

**Expected behavior**
Validation message about not allowed symbol is not displayed

**Screenshots**
topic name

### PR DESCRIPTION
**Pull request by MichaelGonzalezMurillo**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

Fixes #2203 

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [x] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by workshur — APPROVED** [review]
LGTM

**Comment by workshur** [comment]
@armenuikafka Could you please take a look?

**Comment by armenuikafka** [comment]
@workshur works correctly !

**Comment by Haarolean** [comment]
@MichaelGonzalezMurillo super cool, thanks

**Pull request merged**
