### PR TITLE
fixed:#3346

### PR DESCRIPTION
**Pull request by RaajuKanuri**
Issue Broker's configs search by key is case-sensitive is fixed. Changed to identify case-in-sensitive.

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
To fix this issue, I have added the toLocaleLowerCase() call in filter method of the tsx file src/components/Brokers/Broker/Configs/Configs.tsx

**Is there anything you'd like reviewers to focus on?**
I'm good here. It is my good first issue. This is not giving any breaking change to the application. 

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [X] Manually (please, describe, if necessary)
-After the changes, I did build, run and tested the application. 
- [x] Unit checks
- [x] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [X] My changes generate no new warnings (e.g. Sonar is happy)
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by RaajuKanuri** [comment]
Local testing.
image

**Comment by RaajuKanuri** [comment]
@Haarolean , I'm not sure why E2E PR health checks are failing. It was success before I committed the ESLIint error resolution commit. Not a big change in the second commit. I just added empty lines.

**Comment by RaajuKanuri** [comment]
> @RaajuKanuri that's fine, it seems to be flaky a bit

@Haarolean Then Are you going to merge this PR.

**Comment by RaajuKanuri** [comment]
@VladSenyuta & @Haarolean . Could you please review and approve the PR, All checks have passed. Let me know If I need to do anything further.

**Comment by Haarolean** [comment]
@provectus/kafka-frontend PTAL

**Comment by RaajuKanuri** [comment]
> @provectus/kafka-frontend PTAL

@Haarolean are you referring to any one here ? or you are asking me to take another look ?

**Comment by RaajuKanuri** [comment]
> > @provectus/kafka-frontend PTAL
> 
> @Haarolean sorry didn't get you. are you referring to any one here ? or you are asking me to take another look ?

Yeah got you. @provectus/kafka-frontend  is code owner. Thanks

**Review by David-DB88 — APPROVED** [review]

**Comment by RaajuKanuri** [comment]
@provectus/kafka-qa , @Haarolean  could you please approve the PR. Let me know If I need to do anything else.

**Comment by Haarolean** [comment]
@RaajuKanuri thanks for a contribution :)

**Comment by RaajuKanuri** [comment]
> @RaajuKanuri thanks for a contribution :)

Thanks @Haarolean for the opportunity. It is my first Open source contribution. I'm happy to take another one.

**Comment by Haarolean** [comment]
@RaajuKanuri awesome! Welcome to the open-source community! ❤️

**Pull request merged**
