### PR TITLE
Create schema view is too wide

### LINKED ISSUE #2532: Create schema view is too wide
**Describe the bug**
Create schema view is too wide, please make smaller the fields

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Schema registry
2. Press "Create Schema"

**Expected behavior**

View is too wide, make smaller

**Screenshots**
create schema

### PR DESCRIPTION
**Pull request by habrahamyanpro**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
- fixes #2532

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by workshur** [comment]
Could you please add existing functionality for such easy task?

**Comment by workshur** [comment]
> Do you mean put inline style there? Please highlight the part of code 👌

Do not create new options for input.

**Comment by workshur** [comment]
Pls update width of a form container

**Review by workshur — APPROVED** [review]

**Comment by workshur** [comment]
@Haarolean pls take a look?

**Review by Haarolean — APPROVED** [review]
@habrahamyanpro good to merge

**Pull request merged**
