### PR TITLE
fix: ksql request input overflow

### LINKED ISSUE #2721: KSQL: "Execute KSQL Request" Stream properties overlayed by KSQL query window
**Describe the bug**
Layout of the KSQL query window is broken and Stream properties input left border is way under the KSQL query window.

**Set up**
[0939d61](https://github.com/provectus/kafka-ui/commit/0939d61)

**Steps to Reproduce**
1. Open the KSQL tab.
2. Push the "Execute KSQL Request" button
**Actual behavior**
All the stream properties edit fields are under the query window (all the additional ones are as well)
https://user-images.githubusercontent.com/112083452/195013920-933b7580-5f80-4d2c-afab-84ae089d6324.mov

**Expected behavior**
Normal window layout for every field. Including all the additional stream properties.

**Additional context**
Additional stream properties are also under the query window.

### PR DESCRIPTION
**Pull request by devils2ndself**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

Resolves #2721

**What changes did you make?** (Give an overview)

Made KSQL Request -> Stream Properties input tags responsive, resolving the overflow that was before.

**Is there anything you'd like reviewers to focus on?**

Maybe different resolutions. It worked fine at 1080p and was overflowing below 720p. Now should be working just fine at any resolution.

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**
image_2022-09-08_15-10-47

### CODE REVIEW

**Comment by kristi-dev** [comment]
Hey, Artem. Could you, please, put an "x" next to all items below the Checklist, otherwise the build will fail

**Comment by workshur** [comment]
@Haarolean pls take a look 👀

**Review by BulatKha — APPROVED** [review]
Found issue:
KSQL: Container with query "Status" is too narrow #2822

**Review by kristi-dev — APPROVED** [review]

**Comment by devils2ndself** [comment]
> Found issue: KSQL: Container with query "Status" is too narrow #2822

is it something caused by my changes?

**Comment by Haarolean** [comment]
> > Found issue: KSQL: Container with query "Status" is too narrow #2822
> 
> is it something caused by my changes?

dw, we'll do this in a separate one, not sure that's (quickly) fixable. Thanks for the contribution!

**Pull request merged**
