### PR TITLE
update pre-requisite readme file

### PR DESCRIPTION
**Pull request by ShubhamKumar89**
- [ ] **Breaking change?** 
Update the readme file for pre-requisite for kafka-ui. Add dependencies installation for ubuntu.

**What changes did you make?** 
update dependency installation for ubuntu pre-requisite readme file.

**Is there anything you'd like reviewers to focus on?**
@Haarolean 

Issue:  #3392 

**How Has This Been Tested?** 

- [ ] No need to
- [x] Manually
- [ ] Unit checks
- [ ] Integration checks
- [x] Covered by existing automation

**Checklist** 
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

image

Signed-off-by: Shubham Kumar [shubham.kumar@ramanujan.du.ac.in](mailto:shubham.kumar@ramanujan.du.ac.in)

### CODE REVIEW

**Comment by ShubhamKumar89** [comment]
sorry to push this in the `master` branch but I won't be able to move it to the `docs` branch. 
can u help btw!

**Comment by Haarolean** [comment]
@ShubhamKumar89 what's the reason behind creating a duplicate PR?

**Comment by ShubhamKumar89** [comment]
> @ShubhamKumar89 what's the reason behind creating a duplicate PR?

sorry but I have tried to change in the previous PR but not able to do so. 
basically I'm have made a couple of PRs so don't much about how to do that.

**Comment by Haarolean** [comment]
> > @ShubhamKumar89 what's the reason behind creating a duplicate PR?
> 
> sorry but I have tried to change the previous PR but am not able to do so. basically, I had made a couple of PRs so don't know much about how to do that.

Yes, you are able. You made a fork and you can edit the files within a branch of your own fork. 
You can look up on google how to edit files multiple times within a PR.

Feel free to mark #3392 as ready for review once you're done.

**Pull request closed without merging**
