### PR TITLE
Allow Skip Certificates Verification in readiness and liveness probes

### PR DESCRIPTION
**Pull request by joseacl**
- [ ] **Breaking change?** 

**What changes did you make?** (Give an overview)
The changes need for the issue described here https://github.com/provectus/kafka-ui/issues/2923
Basically, I've added in the deployment.yaml of the helm chart, the possibility to skip certification verification from kubernetes when the application is configured with SSL enable.

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually -> Execute helm template for the chart, with default value, and with true value. The outcome in the deployment.yaml manifest is the expected.
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Haarolean** [comment]
Hey, thanks for the contribution. We'll take a look

**Comment by Narekmat** [comment]
@joseacl can you please check scheme in deployment. 
Scheme to use for connecting to the host (HTTP or HTTPS). Defaults to HTTP.

**Comment by joseacl** [comment]
> @joseacl can you please check scheme in deployment. Scheme to use for connecting to the host (HTTP or HTTPS). Defaults to HTTP.

You're right @Narekmat. It's already changed, thanks!

**Review by Narekmat — COMMENTED** [review]
Everything is ok. 
Thank you @joseacl

**Review by Narekmat — APPROVED** [review]

**Comment by Haarolean** [comment]
@joseacl thank you

**Pull request merged**
