### PR TITLE
Add full message details to export

### LINKED ISSUE #2365: Only content data displayed with "Save as a file" and "Copy to clipboard" the Message
**Describe the bug**
Only content data displayed with "Save as a file" and "Copy to clipboard" the Message

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topics
2. Open the Messages tab for one Topic
3. Crete the Messages with Key, Content and Headers
4. Press the "Save as a file" / "Copy to clipboard" from menu

**Expected behavior**
All the Message's data should be copied and exist in a saved file.

**Screenshots**

https://user-images.githubusercontent.com/104780608/182073185-5aaaa867-1a56-4a2c-bbfd-e8fc242f3bc6.mov

**Additional context**

### PR DESCRIPTION
**Pull request by shubhwip**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Add full message details 
Closes #2365

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by shubhwip** [comment]
Copy to cliboard looks like below now
```
{
	"Content": "\"ad proident et nisi adipisicing\"",
	"Offset": 0,
	"Key": "\"sint\"",
	"Partition": 0,
	"Headers": {
		"a": "b"
	},
	"Timestamp": "2022-08-26T10:23:01.771Z"
}
```

Save to file looks like this now
```
"{\n\t\"Content\": \"\\\"ad proident et nisi adipisicing\\\"\",\n\t\"Offset\": 0,\n\t\"Key\": \"\\\"sint\\\"\",\n\t\"Partition\": 0,\n\t\"Headers\": {\n\t\t\"a\": \"b\"\n\t},\n\t\"Timestamp\": \"2022-08-26T10:23:01.771Z\"\n}"
```

**Comment by Haarolean** [comment]
> Copy to cliboard looks like below now
> 
> ```
> {
> 	"Content": "\"ad proident et nisi adipisicing\"",
> 	"Offset": 0,
> 	"Key": "\"sint\"",
> 	"Partition": 0,
> 	"Headers": {
> 		"a": "b"
> 	},
> 	"Timestamp": "2022-08-26T10:23:01.771Z"
> }
> ```
> 
> Save to file looks like this now
> 
> ```
> "{\n\t\"Content\": \"\\\"ad proident et nisi adipisicing\\\"\",\n\t\"Offset\": 0,\n\t\"Key\": \"\\\"sint\\\"\",\n\t\"Partition\": 0,\n\t\"Headers\": {\n\t\t\"a\": \"b\"\n\t},\n\t\"Timestamp\": \"2022-08-26T10:23:01.771Z\"\n}"
> ```
> 
> we can make output of `save to file` same as `copy to clipboard` output which is more readable. What do you think @Haarolean ?

it seems like it should look the same (note the carriage returns and tabs in the line you posted)

**Comment by Haarolean** [comment]
@provectus/kafka-frontend PTAL

**Review by yvaeltercero — APPROVED** [review]
LGTM!

**Review by Kris-K-Dev — APPROVED** [review]

**Comment by Haarolean** [comment]
@shubhwip thank you once again :)

**Pull request merged**
