### PR TITLE
chore(compose): Set readOnly config in kafka-ui.yaml

### PR DESCRIPTION
**Pull request by mohammaddehnavi**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** Set readOnly to docker-compose env for better-understood use of this param

**Is there anything you'd like reviewers to focus on?** No

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary) 
- [x] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Haarolean** [comment]
Hi, how do these changes make it better to understand the usage of the param?

**Comment by mohammaddehnavi** [comment]
> Hi, how do these changes make it better to understand the usage of the param?

When I wanted to use Kafka-ui in my project, I couldn't find any examples of how to use the readOnly feature. It may be good to use it in a docker-compose example.

**Comment by Haarolean** [comment]
> > Hi, how do these changes make it better to understand the usage of the param?
> 
> When I wanted to use Kafka-ui in my project, I couldn't find any examples of how to use the readOnly feature. It may be good to use it in a docker-compose example.

Almost all the misc properties could be found [here](https://docs.kafka-ui.provectus.io/configuration/misc-configuration-properties).
We have a lot of them and printing them all in a docker-compose example (which we have a lot as well, again) would be unwise. Therefore, I guess we could close this :)

**Comment by mohammaddehnavi** [comment]
> > > Hi, how do these changes make it better to understand the usage of the param?
> > 
> > 
> > When I wanted to use Kafka-ui in my project, I couldn't find any examples of how to use the readOnly feature. It may be good to use it in a docker-compose example.
> 
> Almost all the misc properties could be found [here](https://docs.kafka-ui.provectus.io/configuration/misc-configuration-properties). We have a lot of them and printing them all in a docker-compose example (which we have a lot as well, again) would be unwise. Therefore, I guess we could close this :)

Thank you

**Pull request closed without merging**
