### PR TITLE
Issue-2555: add placeholders

### PR DESCRIPTION
**Pull request by vitalymatyushik**
- [x] **Breaking change?** (if so, please describe the impact and migration path for existing application instances) No

**What changes did you make?** Make placeholders visible in inputs on Topic Creation page when they are empty

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by vitalymatyushik** [comment]
@Haarolean I've checked `react-hook-form` api and didn't found fast way to implement the change for the following screen 
image
maybe you can suggest the way how to achieve it or propose different change?

**Comment by Haarolean** [comment]
> @Haarolean I've checked `react-hook-form` api and didn't found fast way to implement the change for the following screen image maybe you can suggest the way how to achieve it or propose different change?

@provectus/kafka-frontend please help

**Comment by Mgrdich** [comment]
> > @Haarolean I've checked `react-hook-form` api and didn't found fast way to implement the change for the following screen image maybe you can suggest the way how to achieve it or propose different change?
> 
> @provectus/kafka-frontend please help

@vitalymatyushik 
https://stackoverflow.com/questions/43964528/append-uneditable-text-to-end-of-input .
I think we have to think of a more css like solution , we can create a component for this or even do a custom code for this one where you can actually set the (7 days) etc in the input  or div attribute and with a pseudo element , and we can get the that attribute value with css and put it with pseudo element as mentioned above.

**Comment by Haarolean** [comment]
@vitalymatyushik and this one?

**Pull request closed without merging**
