### PR TITLE
Display In Sync Replicas (ISR) by Partition on Topic overview

### PR DESCRIPTION
**Pull request by winnie-chiu**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Highlight non-synced replicates partition with bold red.

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by kristi-dev — APPROVED** [review]

**Review by Mgrdich — APPROVED** [review]
If Possible @winnie-chiu can we add some minor test to test this styling toggle.

**Review by Mgrdich — COMMENTED** [review]
If Possible @winnie-chiu can we add some minor test to test this styling toggle.

**Comment by Haarolean** [comment]
@armenuikafka 0.6

**Comment by armenuikafka** [comment]
@BulatKha could you please take a look, seems we need to have more than 1 broker locally to check this

**Review by armenuikafka — APPROVED** [review]
The not synced replicas are highlighted in red 
in sync replicas

**Comment by Haarolean** [comment]
@winnie-chiu thank you

**Pull request merged**
