### PR TITLE
FE: KSQL: Implement sorting

### LINKED ISSUE #3171: KSQL: Implement sorting
**Describe the bug**

1. Neither Tables nor Streams tab have any options to Search, default sorting or user defined sorting by clicking the column names.
2. Not possible to see the Table or Stream details by clicking the row in the table ([task #790](https://github.com/provectus/kafka-ui/issues/790)).

**Expected behavior**

1. Add search by the tab columns.
2. Add the Default sorting for the tab (by the Name?).
3. Add custom sorting by the column names.
4. Table and Stream detailed info is handled in a separate task #790

**Set up**

[f4e6afe](https://github.com/provectus/kafka-ui/commit/f4e6afe)

**Steps to Reproduce**

1. Log in to Kafka UI and navigate to the KSQL DB.

**Screenshots**

image

**Additional context**

@Haarolean requested to create a separate issue from the #2651

### PR DESCRIPTION
**Pull request by michal-cesek**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Enable sorting in the "KSQL DB" section for Tables and Streams lists
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by Mgrdich — APPROVED** [review]

**Comment by michal-cesek** [comment]
@Haarolean looks like it's been forgotten 🤔

**Review by BulatKha — CHANGES_REQUESTED** [review]
Weird behavior (switch to 'Tables' tab from 'Streams' after returning from 'Execute KSQL request' and attempt to sort by the column Name)
@michal-cesek can you please take a look into this?

https://user-images.githubusercontent.com/112083452/226346130-452e2274-a9f3-4251-b4af-ae549b5f667a.mov

**Comment by BulatKha** [comment]
@michal-cesek have you fixed this or is it still in progress? Tried to build it and there is no sorting at KSQL at all.

**Comment by michal-cesek** [comment]
@BulatKha it's still in progress

**Comment by michal-cesek** [comment]
@BulatKha, it's done. I observed a similar bug with the pagination, so the same fix was applied to the pagination change handler.

**Review by BulatKha — APPROVED** [review]
Look ok now

**Comment by BulatKha** [comment]
@Haarolean @michal-cesek looks ok now

**Comment by Haarolean** [comment]
@michal-cesek thank you

**Pull request merged**
