### PR TITLE
#2963 Topic - new topic: Focus is not set to the 'Topic name' field after "Add a new Topic" button is pressed

### LINKED ISSUE #2963: Topics: make the topic name field focused
**Describe the bug**

When a new topic is created via UI, it is easier for user to key in the new topic name and fill in the rest via Tab button from the keyboard.

**Set up**

[6cf8fb3](https://github.com/provectus/kafka-ui/commit/6cf8fb3)

**Steps to Reproduce**

1. Go to topics and click the "Add a topic" button.
**Actual behavior**
No edit field is in the focus, while the page only has them and no other specific fields, that could not be entered from the keyboard.

**Expected behavior**

Topic name would be the first thing to enter on the Create topic page, and user should be able to type it straight in, without clicking on the field first.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by kristi-dev**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Fixed #2963 and similar issues

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [x] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by Mgrdich — APPROVED** [review]

**Review by BulatKha — APPROVED** [review]
Number of partitions now allows entry of the alphanumeric values. It was not allowed before the change

**Review by BulatKha — CHANGES_REQUESTED** [review]
It is possible to enter the alphanumeric values in the Number of partitions field for some reason. Although I don't see changes in commits, that can affect that.
But it doesn't allow it on the master branch deployment. Can you please check?
image

**Comment by Haarolean** [comment]
@BulatKha a bit unrelated and fixed within #3400

**Review by BulatKha — APPROVED** [review]
Happens to be Safari-related. Approving

**Pull request merged**
