### PR TITLE
FE: display consumerGroupID in Reset Offsets page

### PR DESCRIPTION
**Pull request by HurSungYun**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

display `consumerGroupID` instead of `Reset offsets` message in Reset Offsets page.

Currently, `consumerGroupID` is not displayed when changing offsets via Reset Offsets page.

I felt it's a little bit surprising not displaying `consumerGroupID` in the page. Therefore, I would suggest to change UI a bit.

### AS-IS

스크린샷 2023-05-25 오후 8 51 44

### TO-BE

스크린샷 2023-05-25 오후 8 51 02

**Is there anything you'd like reviewers to focus on?**

Nothing special. It's just a UI change.

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [x] No need to
- [ ] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

C5E73463-46FF-467F-B8E2-3D29A20B660A

She's my coworker's cat :)

### CODE REVIEW

**Review by David-DB88 — APPROVED** [review]

**Review by Mgrdich — APPROVED** [review]

**Comment by Mgrdich** [comment]
> @Mgrdich @David-DB88 Thanks for reviewing this PR.
> 
> Should I do anything else to merge this PR? Please let me know what to do if exists.

Everything looks good merge it :)

**Comment by HurSungYun** [comment]
Unfortunately, I have no permission to merge. Can you please merge this PR on behalf of me?

**Comment by Haarolean** [comment]
@HurSungYun sorry for the delay, and thanks for your contribution!

**Comment by HurSungYun** [comment]
No Problem! Appreciated.

**Pull request merged**
