### PR TITLE
Pluggable serde UI changes

### PR DESCRIPTION
**Pull request by yvaeltercero**
Related Issue: https://github.com/provectus/kafka-ui/issues/1777

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by yvaeltercero** [comment]
@Haarolean I am working on resolving broken unit tests but you can start with the review if have you have a chance.

**Comment by yvaeltercero** [comment]
@Haarolean I am done resolving broken tests related to my changes, but I am still seeing issues with a specific logic related to `SCHEMA_REGISTRY`, can you advise what might be causing that? Maybe I need to sync with another branch?

**Comment by Haarolean** [comment]
> @Haarolean I am done resolving broken tests related to my changes, but I am still seeing issues with a specific logic related to `SCHEMA_REGISTRY`, can you advise what might be causing that? Maybe I need to sync with another branch? FYI I noticed that the test fails in the main branch too (pluggable_serde)

let's investigate it later

**Comment by Haarolean** [comment]
> @Haarolean I am done resolving broken tests related to my changes, but I am still seeing issues with a specific logic related to `SCHEMA_REGISTRY`, can you advise what might be causing that? Maybe I need to sync with another branch? FYI I noticed that the test fails in the main branch too (pluggable_serde)

there were serious api changes. Isn't that related? Could you dig into the cause of these tests faillures?

**Comment by Haarolean** [comment]
also produce message doesn't seem to work

**Pull request merged**
