### PR TITLE
solved issue with loader

### PR DESCRIPTION
**Pull request by dwikov**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing applications:)

**What changes did you make?** (Give an overview)
Removed checking for isSubmitting and add reset for isTopicCreated.
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "X" next to an item)

- [X] No need to
- [X] Manually(please, describe, when necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "X" next to an item, otherwise PR will fail)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [X] My changes generate no new warnings(e.g. Sonar is happy)
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

### CODE REVIEW

**Review by workshur — COMMENTED** [review]
I see that `resetUploadedState` dispatches `createTopicAction.failure`. Can we create separate action to reset state instead of using failure?

**Comment by dwikov** [comment]
> I see that `resetUploadedState` dispatches `createTopicAction.failure`. Can we create separate action to reset state instead of using failure?

Yeah that's why I didn't think it was a good idea to do it like this. We can create one more called createTopicAction.cancel and make it responsible for resetting the state.

**Comment by workshur** [comment]
@dwikov I think we can clear state right here https://github.com/provectus/kafka-ui/blob/b60ff8acf698674b4f611abe76776ede3fd0857d/kafka-ui-react-app/src/redux/actions/thunks/topics.ts#L249-L258

**Comment by dwikov** [comment]
> @dwikov I think we can clear state right here, without adding new actions
> 
> https://github.com/provectus/kafka-ui/blob/b60ff8acf698674b4f611abe76776ede3fd0857d/kafka-ui-react-app/src/redux/actions/thunks/topics.ts#L249-L258

We can clear the state of topics here, the issue is with the loader state. As far as I understand, the reducer of the loader changes the state of the loader according to the action called, success fail or fetching.

**Review by workshur — CHANGES_REQUESTED** [review]
We're on the wrong track. Loader reducer used only for async actions

**Pull request closed without merging**
