### PR TITLE
Revert "add labels required by istio"

### PR DESCRIPTION
**Pull request by Haarolean**
Reverts provectus/kafka-ui#2548

### CODE REVIEW

**Comment by Haarolean** [comment]
@PatTheSilent FYI: we've come across this solution due to a problem occurring on our own environment:
```
one or more objects failed to apply, reason: Deployment.apps "dev-kafka-ui" is invalid: spec.template.labels: Invalid value: "f0dca99cd191663a52b0d82f153f99b7c446cb34b837104a7d6e562a0343dcab": must be no more than 63 characters (retried 1 times).```
In our case `Values.image.tag` is set, that's why it fails.
We've noticed that we've overlooked that there's a structure you need, see a few lines lower:
`{{- if .Values.podLabels }}`. So you can pass a map with all the labels you need for istio or any other platform.

**Comment by PatTheSilent** [comment]
Understood. Sorry for causing a problem. Passing podLabels doesn't work for me but I have a workaround that I can stick with.

**Comment by Haarolean** [comment]
> Understood. Sorry for causing a problem. Passing podLabels doesn't work for me but I have a workaround that I can stick with.

No problem, we overlooked that we have podlabels for that :)
Why doesn't it work for you? Please elaborate.

**Comment by PatTheSilent** [comment]
I'm not sure if it's because I don't use helm directly or because the piece of software I use to interface with helm is running `helm template` instead of `helm install` but when I pass something like `{{ .Values.image.tag }}`  in values, it gets templated as a literal string rather than the value of `image.tag`.

**Comment by PatTheSilent** [comment]
well, I'd need for it to work like
```yaml
podLabels:
  version: {{ .Values.image.tag | default .Chart.AppVersion }}
```
which, as I've mentioned, doesn't really work for me and instead of the image tag I get the literal string `{{ .Values.image.tag | default .Chart.AppVersion }}` as the value of the `version` label.
As I've said this isn't the end of the world for me and I have existing workarounds that I used while waiting for the release of my change.

**Pull request merged**
