### PR TITLE
Resolve #2728: Added fontsource usage instead google fonts

### LINKED ISSUE #2728: AirGap: Remove internet dependency / google fonts
Hi!

we are accessing latest kafka-ui via a corporate socks proxy, which does not have internet access.

Would it be possible to embed the fonts in the react-app (as part of static folder e.g.) instead of referencering those online?

https://github.com/provectus/kafka-ui/blob/master/kafka-ui-react-app/index.html#L10

```
    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500&family=Roboto+Mono:wght@400;500&display=swap"
      rel="stylesheet"
    />

```

At the moment, our browser tries to reach following two google font online urls via socks proxy, which leads to a initial load of the kafka-ui of 30 seconds (browser gets a network timeout after 30 seconds):

https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;500&display=swap

https://fonts.googleapis.com/css2?family=Inter:wght@400;500&display=swap

### PR DESCRIPTION
**Pull request by 0leg53**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

Linked issues:
Closes #2728

### CODE REVIEW

**Comment by workshur** [comment]
Hey @0leg53, 
Thank you for contribution!
Unfortunately, we cannot merge your changes yet. Due to the technical peculiarities of building and running the application. 

This PR is blocked by #2372

**Review by Haarolean — APPROVED** [review]

**Review by Haarolean — CHANGES_REQUESTED** [review]
image
yep, doesn't work good with custom context path

**Comment by Haarolean** [comment]
@0leg53 I've added a label "hacktoberfest-accepted" to make sure it does count towards the goal if you're participating

**Comment by 0leg53** [comment]
@Haarolean 
thank you for review. 
how exactly you've got this error? I've tried to run app with `pnpm preview` and font loading looks fine.
image

**Comment by Haarolean** [comment]
@0leg53 you'll have to set a `SERVER_SERVLET_CONTEXT_PATH` property. This is a result of #2372 as Oleg mentioned :)

**Comment by Haarolean** [comment]
@0leg53 hey can you fix the conflicts? I think we're ready to test it out.

**Review by Mgrdich — COMMENTED** [review]
a Question in general , is it  a good behavior to actually include the font in the javascript bundled file, what if we actually put it in a separate `css` file with `font faces` and everything , and include that `css` in the `HTML` itself.

**Comment by Haarolean** [comment]
Done within #3602

**Pull request closed without merging**
