### PR TITLE
FE: Allow to edit active topic message filter

### PR DESCRIPTION
**Pull request by michal-cesek**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Haarolean** [comment]
> @Haarolean, what is @QaseId() annotation used for? I wrote a test for the new functionality, but I need to figure out the value of the id.

it's a test id within our qase.io integration. Unfortunately, it doesn't allow anonymous access right now. We'll fix e2e tests ourselves, that's fine.

**Comment by michal-cesek** [comment]
> > @Haarolean, what is @QaseId() annotation used for? I wrote a test for the new functionality, but I need to figure out the value of the id.
> 
> it's a test id within our qase.io integration. Unfortunately, it doesn't allow anonymous access right now. We'll fix e2e tests ourselves, that's fine.

All right then, from my side, the work is done. Currently, the pipeline fails because of the qaseid todo comment. Once resolved it should pass successfully. 

btw. the implementation of "doesFilterCodeFieldMatchValue" is a little bit hacky because of the editor component. Apparently, it's not that easy to e2e test it using underlying HTML elements.

**Comment by Haarolean** [comment]
@michal-cesek we'll take a look at the tests once we're done with frontend review :)
That might take some time

**Review by Mgrdich — APPROVED** [review]

**Comment by michal-cesek** [comment]
@Haarolean fixed

**Review by Haarolean — APPROVED** [review]
Icon sizes are a bit weird, different from figma, but not sure that figma's version is alright either.

**Comment by Haarolean** [comment]
@michal-cesek thanks for your contribution! The PR will get merged soon.

**Comment by Zeeeeta** [comment]
The filter function doesn't seem to work on 0.7.2 (I mainly used for header field).
Need to fallback to 0.7.1 to get it works.

`headers.market=="XXX"
or
headers["market"] == "XXX"`

Return no result even if data does exist.

**Comment by Haarolean** [comment]
@Zeeeeta this repo is not maintained, please see https://github.com/kafbat/kafka-ui

**Comment by Zeeeeta** [comment]
> @Zeeeeta this repo is not maintained, please see https://github.com/kafbat/kafka-ui

Oh really, since it has release last week, didn't realize that.
Will check the kafbat repo out, thanks.

**Pull request merged**
