### PR TITLE
[Issue-998] Add Recreate topic button in to list of Topic and Details topic Overview

### PR DESCRIPTION
**Pull request by Zorii4**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Add Recreate Topic button, which allows to recreate Topic in one click with same configuration.
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [x] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by workshur — APPROVED** [review]

**Review by NelyDavtyan — APPROVED** [review]

**Comment by sasunprov** [comment]
@workshur I think we should add this logic after merging the new Topic List Table

**Comment by workshur** [comment]
@sasunprov Agree. I will reassign this PR & issue to you

**Comment by sasunprov** [comment]
Will be merged after #1703

**Review by Mgrdich — APPROVED** [review]
Maybe if we have time we can write 
List.tsx and ListItem.tsx cause they have couple of instances that is not covered by test which can be checked by Sonar.

**Pull request merged**
