### PR TITLE
Helm: Add loadBalancerIP attribute for LB svc

### PR DESCRIPTION
**Pull request by nbouron**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

In some cases we need to set the loadBalancerIP with a preprovisioned IP in case of a service of type LoadBalancer, this is why i created this PR.

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

Please Merge Me

### CODE REVIEW

**Review by Narekmat — CHANGES_REQUESTED** [review]
Hello @nbouron. Thank you for your changes.
Please fix versions in Charts.yaml.
-appversion must stay v0.6.2 and -version must be 0.6.3

**Comment by Narekmat** [comment]
@nbouron please keep appversion v0.6.2

**Comment by nbouron** [comment]
Sorry for the mistake, the explanation was clear, it's fixed !

**Comment by Haarolean** [comment]
@nbouron can you rebase please?

**Comment by Haarolean** [comment]
@nbouron the build will fail until the template checkboxes are filled correctly, can you fix that as well?

**Comment by nbouron** [comment]
Fixed

**Comment by Haarolean** [comment]
@nbouron thank you for the contribution!

**Pull request merged**
