### PR TITLE
[Helm] Added annotations for the deployment

### LINKED ISSUE #2748: No custom `annotations` on the level of the `Deployment` metadata
**Describe the bug**

Not really a bug, however, a missing small feature. Deployment object `annotations` should be given as a configuration parameter to the users of the Helm Charts.

A PR can follow to work on that.

**Set up**

Using Helm

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by sherifkayad**
Signed-off-by: Sherif Ayad <sherif.k.ayad@gmail.com>

Fixes #2748 

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**
cat

### CODE REVIEW

**Review by vahagnhayrapetyan — APPROVED** [review]

**Review by vahagnhayrapetyan — APPROVED** [review]

**Comment by sherifkayad** [comment]
@vahagnhayrapetyan @Haarolean can you guys please explain the error of the build-and-test job? I am not sure I quite get it.

**Comment by Haarolean** [comment]
@sherifkayad we've got it broken after a recent push lol. Don't worry, we'll get it fixed

**Comment by sherifkayad** [comment]
@Haarolean hahaa at least good to know I didn't break it with that small PR 😄

**Review by RustamGimadiev — APPROVED** [review]

**Comment by sherifkayad** [comment]
@Haarolean @RustamGimadiev any news folks regarding merging this one? I don't know why the build is still failing here

**Comment by Haarolean** [comment]
> @Haarolean @RustamGimadiev any news folks regarding merging this one? I don't know why the build is still failing here

haven't forgot, don't worry :)

**Comment by Haarolean** [comment]
thank you

**Pull request merged**
